const jobs = [
  {
    id: 1,
    jobtitle: "Frontend Developer",
    company: "Google",
    date: "13-01-2026",
  },
  {
    id: 2,
    jobtitle: "React Native Specialist",
    company: "Meta",
    date: "14-01-2026",
  },
  { id: 3, jobtitle: "Mobile Dev", company: "Amazon", date: "14-01-2026" },
  {
    id: 4,
    jobtitle: "JS Frontend Dev",
    company: "Microsoft",
    date: "15-01-2026",
  },
  {
    id: 5,
    jobtitle: "Flutter Developer",
    company: "Flipkart",
    date: "16-01-2026",
  },
  {
    id: 6,
    jobtitle: "Backend Developer",
    company: "Netflix",
    date: "17-01-2026",
  },
  {
    id: 7,
    jobtitle: "Full Stack Developer",
    company: "Adobe",
    date: "18-01-2026",
  },
  { id: 8, jobtitle: "UI/UX Designer", company: "Airbnb", date: "19-01-2026" },
  { id: 9, jobtitle: "DevOps Engineer", company: "IBM", date: "20-01-2026" },
  {
    id: 10,
    jobtitle: "Node.js Developer",
    company: "PayPal",
    date: "21-01-2026",
  },
  {
    id: 11,
    jobtitle: "Angular Developer",
    company: "Infosys",
    date: "22-01-2026",
  },
  { id: 12, jobtitle: "iOS Developer", company: "Apple", date: "23-01-2026" },
  {
    id: 13,
    jobtitle: "Android Developer",
    company: "Samsung",
    date: "24-01-2026",
  },
  { id: 14, jobtitle: "QA Tester", company: "Wipro", date: "25-01-2026" },
  { id: 15, jobtitle: "Software Engineer", company: "TCS", date: "26-01-2026" },
  {
    id: 16,
    jobtitle: "Data Analyst",
    company: "Accenture",
    date: "27-01-2026",
  },
  {
    id: 17,
    jobtitle: "Machine Learning Engineer",
    company: "OpenAI",
    date: "28-01-2026",
  },
  {
    id: 18,
    jobtitle: "Cybersecurity Analyst",
    company: "Cisco",
    date: "29-01-2026",
  },
  { id: 19, jobtitle: "Cloud Engineer", company: "Oracle", date: "30-01-2026" },
  {
    id: 20,
    jobtitle: "Technical Support Engineer",
    company: "HCL",
    date: "31-01-2026",
  },
  { id: 21, jobtitle: "Product Manager", company: "Zoho", date: "01-02-2026" },
  {
    id: 22,
    jobtitle: "Scrum Master",
    company: "Capgemini",
    date: "02-02-2026",
  },
  {
    id: 23,
    jobtitle: "Game Developer",
    company: "Ubisoft",
    date: "03-02-2026",
  },
  {
    id: 24,
    jobtitle: "Blockchain Developer",
    company: "Coinbase",
    date: "04-02-2026",
  },
  {
    id: 25,
    jobtitle: "Embedded Systems Engineer",
    company: "Intel",
    date: "05-02-2026",
  },
];

module.exports = { jobs };
